export const ACTION_TYPE = {
  SET_THEME: 'SET_THEME',
  SET_USER: 'SET_USER',
  SET_HOTELS: 'SET_HOTELS',
  SET_ORDERED_HOTELS: 'SET_ORDERED_HOTELS',
  RESET_USER: 'RESET_USER',
  RESET_HOTELS: 'RESET_HOTELS',
  SET_COMMENTS: 'SET_COMMENTS',
  ADD_COMMENT: 'ADD_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  SET_ORDERED_HOTEL: 'SET_ORDERED_HOTEL',
  CANCEL_ORDERED_HOTEL: 'CANCEL_ORDERED_HOTEL',
};
